# Generated by Django 5.2.17 on 2026-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, help_text='Username, or empty for the system.', max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('TRASHED', 'Moved to the trash'), ('RESTORED', 'Restored'), ('DELETED', 'Deleted permanently'), ('IMPORTED', 'Imported'), ('BACKED_UP', 'Backed up')], db_index=True, max_length=20)),
                ('label', models.CharField(help_text='What it happened to, e.g. «۲۱۰ — لباسشویی».', max_length=200)),
                ('details', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Extension activity',
                'verbose_name_plural': 'Extension activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
