# Generated by Django 5.2.17 on 2026-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Operator's own 'available / busy' toggle, shown in the reassignment dropdown so a colleague can be picked with the current workload in mind. Meaningless for GUEST/ADMIN roles."),
        ),
    ]