# Generated by Django 5.2.17 on 2026-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last time this operator\'s panel was open (refreshed by the live notification stream\'s heartbeat and by the status endpoint). Auto-assignment only picks operators seen recently — being logged in to the panel is what "on shift" means here.', null=True),
        ),
    ]
