# Generated by Django 5.2.17 on 2026-09-30 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0003_department_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('title_en', models.CharField(blank=True, max_length=150)),
                ('body_en', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event')], default='NEWS', max_length=10)),
                ('audience', models.CharField(choices=[('GUEST', 'Guests'), ('STAFF', 'Staff'), ('BOTH', 'Guests and staff')], db_index=True, default='GUEST', help_text='Who this is for. Guest items also appear on the room TV.', max_length=10)),
                ('event_at', models.DateTimeField(blank=True, help_text='For an event: when it takes place.', null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_pinned', models.BooleanField(default=False, help_text='Keep at the top regardless of date.')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Not shown before this moment.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Empty means it stays up.', null=True)),
                ('icon', models.CharField(default='Megaphone', help_text='A lucide-react icon name, e.g. Megaphone, Music, Waves, Utensils.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Staff items only: leave empty for the whole hotel, or pick a department to show it to that team alone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='departments.department')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News and events',
                'ordering': ['-is_pinned', '-publish_at', '-id'],
            },
        ),
    ]
