# Generated by Django 5.2.17 on 2026-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='auto_assign',
            field=models.BooleanField(default=False, help_text='Hand each new guest ticket straight to the least-busy operator of this department who has the panel open. Off: new tickets wait for a supervisor to assign them.'),
        ),
    ]
