# Generated by Django 5.2.17 on 2026-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_auto_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='working_hours',
            field=models.CharField(blank=True, help_text="Free text, e.g. «۰۸:۰۰ تا ۲۰:۰۰». Shown beside this department's numbers in the staff phone directory (apps/extensions), so whoever is about to ring knows whether anybody is there.", max_length=120),
        ),
    ]
