from django.urls import path

from .views import (
    AdminStatsSummaryView,
    CategoryDetailView,
    CategoryListCreateView,
    GuestTicketAttachmentCreateView,
    GuestTicketDetailView,
    GuestTicketListCreateView,
    GuestTicketRateView,
    GuestTicketReopenView,
    OperatorColleaguesListView,
    OperatorNewTicketCountView,
    OperatorOverdueTicketCountView,
    OperatorTicketAttachmentCreateView,
    OperatorTicketDetailView,
    OperatorTicketListView,
    OperatorTicketAssignView,
    QuickRequestTemplateListView,
    TicketHistoryView,
    TicketNoteCreateView,
)

urlpatterns = [
    path(
        "admin/stats/summary/",
        AdminStatsSummaryView.as_view(),
        name="admin-stats-summary",
    ),
    path(
        "categories/",
        CategoryListCreateView.as_view(),
        name="category-list",
    ),
    path(
        "categories/<int:pk>/",
        CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path(
        "quick-templates/",
        QuickRequestTemplateListView.as_view(),
        name="quick-template-list",
    ),
    path(
        "tickets/",
        GuestTicketListCreateView.as_view(),
        name="guest-ticket-list-create",
    ),
    path(
        "tickets/<int:pk>/",
        GuestTicketDetailView.as_view(),
        name="guest-ticket-detail",
    ),
    path(
        "tickets/<int:pk>/rate/",
        GuestTicketRateView.as_view(),
        name="guest-ticket-rate",
    ),
    path(
        "tickets/<int:pk>/reopen/",
        GuestTicketReopenView.as_view(),
        name="guest-ticket-reopen",
    ),
    path(
        "tickets/<int:pk>/attachments/",
        GuestTicketAttachmentCreateView.as_view(),
        name="guest-ticket-attachment-create",
    ),
    path(
        "operator/tickets/",
        OperatorTicketListView.as_view(),
        name="operator-ticket-list",
    ),
    path(
        "operator/tickets/new-count/",
        OperatorNewTicketCountView.as_view(),
        name="operator-ticket-new-count",
    ),
    path(
        "operator/tickets/overdue-count/",
        OperatorOverdueTicketCountView.as_view(),
        name="operator-ticket-overdue-count",
    ),
    path(
        "operator/tickets/<int:pk>/",
        OperatorTicketDetailView.as_view(),
        name="operator-ticket-detail",
    ),
    path(
        "operator/tickets/<int:pk>/assign/",
        OperatorTicketAssignView.as_view(),
        name="operator-ticket-assign",
    ),
    path(
        "operator/tickets/<int:pk>/history/",
        TicketHistoryView.as_view(),
        name="operator-ticket-history",
    ),
    path(
        "operator/tickets/<int:pk>/notes/",
        TicketNoteCreateView.as_view(),
        name="operator-ticket-notes",
    ),
    path(
        "operator/tickets/<int:pk>/attachments/",
        OperatorTicketAttachmentCreateView.as_view(),
        name="operator-ticket-attachment-create",
    ),
    path(
        "operator/colleagues/",
        OperatorColleaguesListView.as_view(),
        name="operator-colleagues-list",
    ),
]