from django.urls import path

from .views import (
    CategoryDetailView,
    CategoryListCreateView,
    GuestTicketDetailView,
    GuestTicketListCreateView,
    OperatorColleaguesListView,
    OperatorNewTicketCountView,
    OperatorTicketDetailView,
    OperatorTicketListView,
    OperatorTicketAssignView,
    TicketHistoryView,
    TicketNoteCreateView,
)

urlpatterns = [
    path(
        "categories/",
        CategoryListCreateView.as_view(),
        name="category-list",
    ),
    path(
        "categories/<int:pk>/",
        CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path(
        "tickets/",
        GuestTicketListCreateView.as_view(),
        name="guest-ticket-list-create",
    ),
    path(
        "tickets/<int:pk>/",
        GuestTicketDetailView.as_view(),
        name="guest-ticket-detail",
    ),
    path(
        "operator/tickets/",
        OperatorTicketListView.as_view(),
        name="operator-ticket-list",
    ),
    path(
        "operator/tickets/new-count/",
        OperatorNewTicketCountView.as_view(),
        name="operator-ticket-new-count",
    ),
    path(
        "operator/tickets/<int:pk>/",
        OperatorTicketDetailView.as_view(),
        name="operator-ticket-detail",
    ),
    path(
        "operator/tickets/<int:pk>/assign/",
        OperatorTicketAssignView.as_view(),
        name="operator-ticket-assign",
    ),
    path(
        "operator/tickets/<int:pk>/history/",
        TicketHistoryView.as_view(),
        name="operator-ticket-history",
    ),
    path(
        "operator/tickets/<int:pk>/notes/",
        TicketNoteCreateView.as_view(),
        name="operator-ticket-notes",
    ),
    path(
        "operator/colleagues/",
        OperatorColleaguesListView.as_view(),
        name="operator-colleagues-list",
    ),
]