# Generated by Django 5.2.17 on 2026-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('body_en', models.TextField(blank=True)),
                ('icon', models.CharField(default='Info', help_text='A lucide-react icon name, e.g. Wifi, Coffee, Clock, Phone.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hotel info',
                'verbose_name_plural': 'Hotel info',
                'ordering': ['order', 'title'],
            },
        ),
    ]
