# Generated by Django 5.2.17 on 2026-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_hotel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Set when the PMS reports the check-out. The room is freed and `room` is cleared, which is what blocks the guest from logging in again; their past tickets are untouched.', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='expected_check_out',
            field=models.DateField(blank=True, help_text='Departure date as the PMS last reported it (moves when a stay is extended).', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='reservation_id',
            field=models.CharField(blank=True, help_text="The PMS's reservation number for the current stay, when it sends one.", max_length=120),
        ),
    ]
