# Generated by Django 5.2.17 on 2026-08-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('tickets', '0003_tickethistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, help_text='Filled in by the operator when resolving the ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.ForeignKey(default=1, help_text="Snapshot of the guest's room at the time the ticket was created.", on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='rooms.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category'),
            preserve_default=False,
        ),
    ]