# Generated by Django 5.2.17 on 2026-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='response_sla_minutes',
            field=models.PositiveIntegerField(default=10, help_text='First-response target, in minutes: how soon an operator must start on a ticket (move it to IN_PROGRESS). Separate from sla_minutes (the resolution target): a guest mostly wants to know quickly that someone is on it. Capped at sla_minutes.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text="When the ticket first moved to IN_PROGRESS — the first-response SLA's finish line. Set once by save(), never cleared, even if the ticket is handed back to OPEN later.", null=True),
        ),
    ]
