# Generated by Django 5.2.17 on 2026-09-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_auto_assign'),
        ('tickets', '0011_backfill_first_response_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Set when a supervisor merged this ticket into another one as a duplicate (it is then CANCELLED). See services.merge_tickets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('MERGED', 'Merged')], max_length=30),
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label shown in the picker.', max_length=100)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, help_text='Blank = available to every department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='departments.department')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
