# Generated by Django 5.2.17 on 2026-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PMS sync state',
                'verbose_name_plural': 'PMS sync state',
            },
        ),
        migrations.CreateModel(
            name='PmsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WEBHOOK', 'Webhook (PMS called us)'), ('PULL', 'Pull (we asked the PMS)'), ('SIMULATOR', 'Simulator')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=30)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('payload', models.JSONField(help_text='Exactly what the PMS sent, before any mapping.')),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored (duplicate)'), ('REJECTED', 'Rejected (invalid payload)')], db_index=True, max_length=20)),
                ('error', models.TextField(blank=True)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('reservation_id', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='pms_pmseven_event_t_0ce8e1_idx')],
            },
        ),
    ]
