# Generated by Django 5.2.17 on 2026-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_IN_PROGRESS', 'Work started'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_CANCELLED', 'Ticket cancelled')], max_length=30, unique=True)),
                ('body', models.TextField(help_text='Placeholders: {title} {ticket_id} {department} {room} {hotel}')),
                ('is_active', models.BooleanField(default=True, help_text='Off = no SMS for this event.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='event',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket created'), ('TICKET_IN_PROGRESS', 'Work started'), ('TICKET_RESOLVED', 'Ticket resolved'), ('TICKET_CANCELLED', 'Ticket cancelled')], max_length=30),
        ),
    ]
