# Generated by Django 5.2.17 on 2026-09-22 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_ops', '0004_drop_legacy_department_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text="The operator who filed it from their own department's panel. Empty when IT logged a phoned-in request (see requested_by_name).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_requests_filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
