# Generated by Django 5.2.17 on 2026-09-25 00:53

import apps.it_ops.models
import apps.tickets.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_ops', '0005_department_request_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Pre-filled into the description box; the operator edits it before sending.')),
                ('icon', models.CharField(default='Wrench', help_text="A lucide-react icon name (e.g. 'Printer', 'Wifi', 'Monitor'). Not validated here: an unknown name falls back to a generic icon.", max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'verbose_name': 'IT request template',
                'verbose_name_plural': 'IT request templates',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='departmentrequest',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='departmentrequest',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentrequest',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5, set once by the requesting department after the work is COMPLETED.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='DepartmentRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image only (jpg/jpeg/png/webp/gif), max MAX_ATTACHMENT_SIZE_MB.', upload_to=apps.it_ops.models.it_request_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.tickets.models.validate_attachment_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='it_ops.departmentrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_request_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
